import os
import numpy as np
import pandas as pd
from scipy.optimize import minimize

def run_black_litterman():
    print("[SYSTEM INFO] Initializing Black-Litterman Optimization Engine...")
    
    # 1. Load fresh data generated by the Ingestion Layer
    data_path = "data/market_universe.csv"
    if not os.path.exists(data_path):
        print(f"[ERROR] Data file not found at {data_path}. Run data ingestion first.")
        return
        
    df = pd.read_csv(data_path, index_col=0, parse_dates=True)
    returns = df.pct_change().dropna()
    
    # 2. Establish Baseline Market parameters
    num_assets = len(df.columns)
    W_mkt = np.array([1.0 / num_assets] * num_assets)  # Assume equal-weight baseline benchmark
    Sigma = returns.cov().to_numpy() * 252            # Annualized Covariance Matrix
    delta = 2.5                                       # Standard market risk aversion coefficient
    
    # Compute Implied Equilibrium Returns (\Pi = \delta * \Sigma * W_mkt)
    Pi = delta @ Sigma @ W_mkt
    
    # 3. Formulate Quantitative Views (P, Q, \Omega)
    # View: Top momentum asset will outperform, bottom will underperform
    asset_momentum = returns.mean() * 252
    top_asset_idx = np.argmax(asset_momentum.to_numpy())
    bottom_asset_idx = np.argmin(asset_momentum.to_numpy())
    
    P = np.zeros((1, num_assets))
    P[0, top_asset_idx] = 1
    P[0, bottom_asset_idx] = -1
    
    Q = np.array([0.05])  # View Vector: Expect top asset to outperform bottom by 5% annualized
    
    tau = 0.05            # Scaling constant for baseline uncertainty
    Omega = np.array([[tau * (P @ Sigma @ P.T)[0,0]]]) # View uncertainty matrix scaled by historical variance
    
    # 4. Execute Black-Litterman Formula (Bayesian Matrix Blending)
    try:
        inv_tau_Sigma = np.linalg.inv(tau * Sigma)
        inv_Omega = np.linalg.inv(Omega)
        
        # Combined Expected Returns Matrix Equation
        first_term = np.linalg.inv(inv_tau_Sigma + P.T @ inv_Omega @ P)
        second_term = inv_tau_Sigma @ Pi + P.T @ inv_Omega @ Q
        E_R = first_term @ second_term
        
        print(f"[MATH SUCCESS] Adjusted Expected Returns vector computed safely: {E_R}")
    except np.linalg.LinAlgError:
        print("[ERROR] Matrix inversion failed. Defaulting to historical parameters.")
        E_R = returns.mean().to_numpy() * 252
        
    # 5. Mean-Variance Optimization using BL returns
    def portfolio_variance(weights):
        return weights.T @ Sigma @ weights
        
    constraints = ({'type': 'eq', 'fun': lambda w: np.sum(w) - 1.0}) # Long-only fully invested budget
    bounds = [(0.0, 1.0) for _ in range(num_assets)]
    
    initial_guess = W_mkt
    optimized_result = minimize(portfolio_variance, initial_guess, method='SLSQP', bounds=bounds, constraints=constraints)
    
    # 6. Export and Log Results
    os.makedirs("output", exist_ok=True)
    weights_df = pd.DataFrame({
        "Asset": df.columns,
        "Optimal_Weight": np.round(optimized_result.x, 4)
    })
    weights_df.to_csv("output/bl_optimized_weights.csv", index=False)
    print(f"[SUCCESS] Black-Litterman Optimization complete. Weights saved to output/bl_optimized_weights.csv")

if __name__ == "__main__":
    run_black_litterman()
